spring:
  datasource:
    url: jdbc:sqlserver://springbootsqlserverdbazure.database.windows.net:1433;database=springbootazuresqldb;user=springbootsqlserverdbazure@springbootsqlserverdbazure;password={password@123};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: springbootsqlserverdbazure
    password: password@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      
server:
  port: 9191